server:
  port: 7001
spring:
  application:
    name: webflux-demo
  profiles:
    active: ${demo.spring.profile}
  r2dbc:
        url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
        username: sa
        password:
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
          ddl-auto: update
logging:
  level:
    root: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always