server:
  port: 8080
spring:
  application:
    name: webflux-demo
  profiles:
    active: ${demo.spring.profile}
  r2dbc:
        url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
        username: sa
        password:
logging:
  level:
    root: DEBUG
  config: classpath:log4j2-file.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always