openapi: 3.0.3
info:
  title: Employee API
  description: API for managing employee records.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /employees/admin/all:
    get:
      tags:
        - Employee
      summary: Get all employees
      operationId: getAllEmployees
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'

  /employees/admin/search:
    get:
      tags:
        - Employee
      summary: Search employees
      operationId: searchEmployees
      parameters:
        - name: searchTerm
          description: Search term will search in first name, last name, date of birth, email, address
          in: query
          required: false
          schema:
            type: string
        - name: dateOfBirth
          in: query
          description: Sort by date of birth
          required: false
          schema:
            $ref: '#/components/schemas/SortDirection'
        - name: salary
          in: query
          description: Sort by salary
          required: false
          schema:
            $ref: '#/components/schemas/SortDirection'
        - name: serviceYears
          in: query
          description: Sort by service years
          required: false
          schema:
            $ref: '#/components/schemas/SortDirection'
        - name: position
          in: query
          description: Filter by position type 
          required: false
          schema:
            $ref: '#/components/schemas/EmployeePositionType'
        - name: status
          in: query
          description: Filter by status type
          required: false
          schema:
            $ref: '#/components/schemas/EmployeeStatusType'
        - name: salaryMin
          in: query
          required: false
          schema:
            type: number
        - name: salaryMax
          in: query
          required: false
          schema:
            type: number
        - name: serviceYearsMin
          in: query
          required: false
          schema:
            type: integer
        - name: serviceYearsMax
          in: query
          required: false
          schema:
            type: integer
        - name: pageIndex
          in: query
          description: Zero-based page index (0..N)
          required: false
          schema:
            type: integer
            default: 0
        - name: pageSize
          in: query
          description: The size of the page to be returned
          required: false
          schema:
            type: integer
            default: 25
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageEmployee'

  /employees/admin/find/{id}:
    get:
      tags:
        - Employee
      summary: Get employee by ID
      operationId: getEmployeeById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Employee object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'

  /employees/admin/findfull/{id}:
    get:
      tags:
        - Employee
      summary: Get employee by ID
      operationId: getEmployeeFullById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Employee object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeFull'

  /employees/admin/audit/{id}:
    get:
      tags:
        - Employee
      summary: Get employee's record audit trail by ID
      operationId: getEmployeeAuditById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Employee object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeAuditResponse'

  /employees/admin/serviceyear/{serviceYears}:
    get:
      tags:
        - Employee
      summary: Get employees by service years less than the specified value
      operationId: getEmployeesByServiceYearsLessThan
      parameters:
        - name: serviceYears
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'

  /employees/admin/add:
    post:
      tags:
        - Employee
      summary: Add a new employee
      operationId: addEmployee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeAddRequest'
      responses:
        '200':
          description: Newly created employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeApiResponse'

  /employees/admin/update/{id}:
    put:
      tags:
        - Employee
      summary: update an employee
      operationId: updateEmployee
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeUpdateRequest'
      responses:
        '200':
          description: Updated employee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeApiResponse'

  /employees/admin/status/{id}:
    patch:
      tags:
        - Employee
      summary: change employee's status
      operationId: changeEmployeeStatus
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: status
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/EmployeeStatusType'
      responses:
        '200':
          description: change employee's status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'

components:
  parameters:
    pageParam:
      in: query
      name: page
      schema:
        type: integer
        default: 0
      description: Zero-based page index (0..N)
    sizeParam:
      in: query
      name: size
      schema:
        type: integer
        default: 25
      description: The size of the page to be returned
    sortParam:
      in: query
      name: sort
      schema:
        type: array
        items:
          type: string
      description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
  schemas:
    PaginationResponse:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
          default: 0
        totalPages:
          type: integer
          default: 0
        first:
          type: boolean
        last:
          type: boolean
        number:
          type: integer
        pageable:
          $ref: '#/components/schemas/Pageable'
        empty:
          type: boolean
        content:
          type: array
          items: {}
    Pageable:
      type: object
      format: pageable
      properties:
        page:
          type: integer
          minimum: 0
        size:
          type: integer
          minimum: 1
        sort:
          type: array
          items:
            type: string
    SortOptions:
      type: object
      properties:
        dateOfBirth:
          $ref: '#/components/schemas/SortDirection'
        salary:
          $ref: '#/components/schemas/SortDirection'
        serviceYears:
          $ref: '#/components/schemas/SortDirection'
    SortDirection:
      type: string
      enum:
        - ASC
        - DESC
    FilterOptions:
      type: object
      properties:
        position:
          type: boolean
          default: false
        status:
          type: boolean
          default: false
    EmployeeStatusType:
      type: string
      enum:
        - ACTIVE
        - INACTIVE
    EmployeePositionType:
      type: string
      enum:
        - ADMIN
        - MANAGER
        - DEVELOPER
        - BA
        - QA
        - HR
        - FINANCE
        - MARKETING
        - SALES
        - RETIRED
    AuditOperationType:
      type: string
      enum:
        - ADD
        - UPDATE
    Employee:
      type: object
      properties:
        id:
          type: number
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        dateOfBirth:
          type: string
          format: date
        position:
          type: string
        salary:
          type: number
          format: double
        serviceYears:
          type: integer
          format: int32
        address:
          type: string
        status:
          type: string
    PageEmployee:
      type: object
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Employee'
              default: []
    EmployeeFull:
      type: object
      properties:
        id:
          type: number
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        dateOfBirth:
          type: string
          format: date
        position:
          type: string
        salary:
          type: number
          format: double
        serviceYears:
          type: integer
          format: int32
        address:
          type: string
        sinNumber:
          type: string
        driverLicenceNumber:
          type: string
        status:
          type: string
    EmployeeAddRequest:
      type: object
      required:
        - firstName
        - lastName
        - email
        - dateOfBirth
        - position
        - salary
        - serviceYears
        - address
        - sinNumber
        - status
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        dateOfBirth:
          type: string
          format: date
        position:
          type: string
        salary:
          type: number
          format: float
        serviceYears:
          type: integer
          format: int32
        address:
          type: string
        sinNumber:
          type: string
        driverLicenceNumber:
          type: string
        status:
          type: string
    EmployeeUpdateRequest:
      type: object
      properties:
        employee:
          $ref: '#/components/schemas/EmployeeFull'
    EmployeeApiResponse:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
        employee:
          $ref: '#/components/schemas/EmployeeFull'
    EmployeeAuditResponse:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
        auditItems:
          type: array
          items:
            $ref: '#/components/schemas/auditItem'
    EmployeeAuditData:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        dateOfBirth:
          type: string
          format: date
        position:
          type: string
        salary:
          type: number
          format: double
        serviceYears:
          type: integer
          format: int32
        address:
          type: string
        sinNumber:
          type: string
        driverLicenceNumber:
          type: string
        status:
          type: string
    auditItem:
      type: object
      properties:
        username:
          type: string
          default: ADMIN
        field:
          type: string
        oldValue:
          type: string
        newValue:
          type: string
        modifiedDate:
          type: string
          format: date
