openapi: 3.0.1
info:
  title: Health API
  description: API for ping and health check
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /health:
    get:
      tags:
        - Health
      summary: Health end point for LB
      operationId: health
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example: "OK"